### PR TITLE
Fix checkstyle errors and add JUnit tests

### LINKED ISSUE #57: Checkstyle and code quality improvements
Can be reopened if new PRs need checkstyle and code quality fix

### PR DESCRIPTION
**Pull request by clarencepohh**
Closes #57 
JUnit tests were added for TaskManagerException class methods.

Need to look into text-ui-testing .sh/.bat files to fix GitHub CI failures.
Please do look through the checkstyle changes and let me know if there is anything to be changed.

### CODE REVIEW

File: src/main/java/data/TaskManager.java [hunk 1]
```diff
@@ -1,18 +1,24 @@
 package data;
 
-import Time.WeekView;
+import time.WeekView;
```
Comment (NicholasTanYY) [inline src/main/java/data/TaskManager.java:3]: Good spot! Package names should definitely be in lowercase.

File: src/main/java/data/TaskManagerException.java [hunk 2]
```diff
@@ -1,60 +1,16 @@
...
 import java.util.List;
 
 public class TaskManagerException extends Exception {
 
-    public static final String NOT_CURRENT_WEEK_MESSAGE = "The date must be within the current week. Please try again.";
-    public static final String NOT_CURRENT_MONTH_MESSAGE = "The date must be within the current month. Please try again.";
+    public static final String NOT_CURRENT_WEEK_MESSAGE =
+            "The date must be within the current week. Please try again.";
+    public static final String NOT_CURRENT_MONTH_MESSAGE =
+            "The date must be within the current month. Please try again.";
```
Comment (NicholasTanYY) [inline src/main/java/data/TaskManagerException.java:13]: This makes the code neater and easier to read.

**Review by NicholasTanYY — COMMENTED** [review]
Overall, great changes made to improve coding standards! This is ready for merging LGTM.

**Comment by NicholasTanYY** [comment]
We will next review why CI build are failing.
